class_name Traducoes
extends RefCounted
## As telas em inglês (o Sprint E). O português é a língua do jogo e a chave:
## cada texto que o Desenho e o Glifo desenham passa por `traduzir`, que acha
## a frase exata na tabela ou, com números no meio, um dos padrões. O que não
## tem tradução sai como está.
##
## O porquê de cada veredito (o que foi medido) e o relatório vêm do núcleo em
## C e ficam em português.

static var idioma := "pt_BR"
static var _padroes: Array = []  # [RegEx, substituição]

const EN := {
	# o título, os créditos, o lobby
	"Quatro DualSense no mesmo sofá.": "Four DualSense on the same couch.",
	"Nenhum controle encontrado.": "No controller found.",
	"Conecte um DualSense por USB ou Bluetooth.": "Connect a DualSense over USB or Bluetooth.",
	"Jogar no teclado · Enter": "Play on the keyboard · Enter",
	"Começar": "Start",
	"Créditos": "Credits",
	"Voltar": "Back",
	"Quem joga": "Who plays",
	"Aperte ✕ no seu controle para entrar.": "Press ✕ on your controller to join.",
	"Todos prontos": "Everyone ready",
	"Entrar": "Join",
	"Pronto": "Ready",
	"Sair": "Leave",
	"Opções": "Options",
	"Simulado": "Simulated",
	"·  Simulado": "·  Simulated",
	"SDL virtual": "SDL virtual",
	"Luz": "Light",
	"Humano": "Human",
	"Orc": "Orc",
	"Espada e escudo": "Sword and shield",
	"Lança": "Spear",
	"Lança e escudo": "Spear and shield",
	"Poção": "Potion",
	"Sem controle": "No controller",
	"O controle saiu.": "The controller left.",
	"Religue o mesmo para voltar.": "Plug the same one back in to return.",
	"Liberar o lugar": "Free the seat",
	"Segure para trocar": "Hold to switch",
	# o HUD e o salão
	"Diagnóstico": "Diagnostics",
	"Pausa": "Pause",
	"Em breve": "Soon",
	"Seção 9 · □ a partida · △ a Prova de Fogo": "Section 9 · □ match · △ Trial by Fire",
	# as salas: o nome e o verbo
	"A Centelha": "The Spark",
	"A Viga": "The Beam",
	"O Molde": "The Mold",
	"O Impacto": "The Impact",
	"A Galeria": "The Gallery",
	"O Canto": "The Song",
	"Os Caminhos": "The Paths",
	"Caminhos": "The Paths",
	"A Voz": "The Voice",
	"A Prova": "The Trial",
	"Aperte o botão da runa antes do anel fechar.": "Press the rune's button before the ring closes.",
	"Equilibre, mire e martele.": "Balance, aim and hammer.",
	"Trace, abra e carimbe o molde.": "Trace, open and stamp the mold.",
	"Sinta o golpe e levante o escudo do lado.": "Feel the blow and raise the shield on that side.",
	"Sinta o gatilho e atire.": "Feel the trigger and shoot.",
	"Ouça o canto e repita o ritmo.": "Listen to the song and repeat the rhythm.",
	"Ande no escuro e sinta o caminho.": "Walk in the dark and feel the path.",
	"Chame o guardião e fique mudo.": "Call the guardian and stay quiet.",
	"Brasa contra Maré.": "Ember against Tide.",
	# as features
	"Botões": "Buttons",
	"Analógicos": "Sticks",
	"Gatilhos analógicos": "Analog triggers",
	"Giroscópio": "Gyroscope",
	"Acelerômetro": "Accelerometer",
	"Touchpad, dois dedos": "Touchpad, two fingers",
	"Touchpad, clique": "Touchpad, click",
	"Motor forte (esquerda)": "Strong motor (left)",
	"Motor fraco (direita)": "Weak motor (right)",
	"Vibração só no controle certo": "Rumble only on the right controller",
	"Lightbar": "Light bar",
	"Gatilho: resistência": "Trigger: resistance",
	"Gatilho: arma": "Trigger: weapon",
	"Gatilho: vibração": "Trigger: vibration",
	"LEDs de jogador": "Player LEDs",
	"Alto-falante do controle": "Controller speaker",
	"Háptica por áudio": "Audio haptics",
	"Microfone": "Microphone",
	"Mudo do microfone": "Microphone mute",
	"LED do microfone": "Microphone LED",
	"Tudo junto": "Everything at once",
	# o aviso, o jogo e o veredito
	"✕ Quando pronto": "✕ When ready",
	"Aguardando": "Waiting",
	"✓ Pronto": "✓ Ready",
	"Trocar": "Switch",
	"Testar": "Test",
	"Não achado": "Not found",
	"✓ PASSOU": "✓ PASSED",
	"✗ FALHOU": "✗ FAILED",
	"— NÃO MEDIDO": "— NOT MEASURED",
	"Voltar ao salão": "Back to the hall",
	"Seguir a Prova de Fogo": "Continue the Trial by Fire",
	"O livro da sessão": "The session book",
	"O placar": "The scoreboard",
	"Prova às cegas: o diagnóstico volta no fim da sala": "Blind test: diagnostics return at the end of the room",
	# A Centelha, A Viga, O Molde
	"Clique quando brilhar": "Click when it glows",
	"Gire para mirar": "Turn to aim",
	"Incline contra o vento": "Lean against the wind",
	"Mira": "Aim",
	"Arremessa": "Throw",
	"Atira": "Shoot",
	"Trace o eta, o H de Hefesto": "Trace the eta, Hefesto's H",
	"Trace o lambda, em ordem": "Trace the lambda, in order",
	"Trace o sigma, em ordem": "Trace the sigma, in order",
	"Dois dedos: afaste": "Two fingers: spread",
	"Agora junte os dedos": "Now pinch",
	# O Impacto, A Galeria
	"Que cor está a sua luz?": "What color is your light?",
	"Âmbar": "Amber",
	"Ciano": "Cyan",
	"Violeta": "Violet",
	"Branco": "White",
	"Isso: a luz obedeceu": "Right: the light obeyed",
	"Isso: as luzinhas obedeceram": "Right: the lights obeyed",
	"Isso: o peso": "Right: the weight",
	"Isso: o tremor": "Right: the tremor",
	"Isso: parede e clique": "Right: wall and click",
	"Isso: solto": "Right: loose",
	"O armeiro recarregou. Quantas luzinhas acesas?": "The armorer reloaded. How many lights are on?",
	"Pistola": "Pistol",
	"Metralhadora": "Machine gun",
	"Arco": "Bow",
	"Sem arma": "No weapon",
	"Recarregue": "Reload",
	"Martelada!": "Hammer blow!",
	"Esquerda": "Left",
	"Direita": "Right",
	# a partida, o placar, o pódio
	"A partida": "The match",
	"Salas": "Rooms",
	"Ordem": "Order",
	"Ritmo": "Pace",
	"A do percurso": "The route's",
	"Sorteada": "Shuffled",
	"Primeira vez": "First time",
	"Normal": "Normal",
	"Rápido": "Fast",
	"Linha": "Row",
	"O pódio": "The podium",
	"Nesta sala": "This room",
	"Da noite": "Tonight",
	"Salas vencidas": "Rooms won",
	"Outra partida": "Another match",
	# as opções
	"Sessão": "Session",
	"Gatilhos": "Triggers",
	"Vibração": "Rumble",
	"Volume da TV": "TV volume",
	"Volume do controle": "Controller volume",
	"Movimento": "Motion",
	"Inteiro": "Full",
	"Reduzido": "Reduced",
	"Reações": "Reactions",
	"Todas": "All",
	"Só do jogo": "Game only",
	"Nenhuma": "None",
	"Lado B": "Side B",
	"Seguir": "Continue",
	"Flashes": "Flashes",
	"Tela": "Screen",
	"Texto": "Text",
	"Idioma": "Language",
	"Desligado": "Off",
	"Fraco": "Weak",
	"Forte": "Strong",
	"Ligado": "On",
	"Ligados": "On",
	"Desligados": "Off",
	"Janela": "Window",
	"Tela cheia": "Fullscreen",
	"Grande": "Large",
	"Tempo": "Timing",
	"Tocar no tempo": "Tap on the beat",
	# O Canto, Os Caminhos, A Voz, A Prova
	"Alto-falante": "Speaker",
	"O canto saiu do seu controle?": "Did the song come from your controller?",
	"Ouça o canto": "Listen to the song",
	"3 cantos seus": "3 songs of yours",
	"Só você na arena": "Just you in the arena",
	"Foi no meu": "It was mine",
	"Não foi": "It wasn't",
	"Repita o ritmo": "Repeat the rhythm",
	"Isso: era da TV": "Right: it was the TV",
	"Isso: era seu": "Right: it was yours",
	"Placa virtual do controle simulado": "Virtual card of the simulated controller",
	"Simulado: quatro canais, como no cabo": "Simulated: four channels, as on the cable",
	"Que chão é esse?": "What ground is this?",
	"Ande e sinta o chão": "Walk and feel the ground",
	"Grama": "Grass",
	"Cascalho": "Gravel",
	"Metal": "Metal",
	"Água": "Water",
	"Não senti": "Didn't feel it",
	"Tropeçou!": "Tripped!",
	"Isso: um baque macio": "Right: a soft thud",
	"Isso: quatro estalos": "Right: four clicks",
	"Isso: um golpe que ressoa": "Right: a ringing blow",
	"Isso: duas ondas": "Right: two waves",
	"Isso: a pedra era da esquerda": "Right: the stone was on the left",
	"Isso: a pedra era da direita": "Right: the stone was on the right",
	"Treino: sinta um baque macio": "Practice: feel a soft thud",
	"Treino: sinta quatro estalos": "Practice: feel four clicks",
	"Treino: sinta um golpe que ressoa": "Practice: feel a ringing blow",
	"Treino: sinta duas ondas": "Practice: feel two waves",
	"Como está a luz do microfone?": "How is the microphone light?",
	"Acesa": "On",
	"Apagada": "Off",
	"Piscando": "Blinking",
	"Olhe o controle…": "Look at the controller…",
	"A luz do microfone": "The microphone light",
	"Silêncio": "Silence",
	"Silêncio: o guardião dorme": "Silence: the guardian sleeps",
	"O silêncio de todos": "Everyone's silence",
	"Quieto": "Quiet",
	"Sua vez: chame!": "Your turn: call!",
	"Fale alto: chame o guardião": "Speak up: call the guardian",
	"Chamou ✓": "Called ✓",
	"Fique mudo": "Mute",
	"Mudo": "Muted",
	"Mudo ✓": "Muted ✓",
	"O mudo": "The mute",
	"Mudos, sussurrem": "Muted, whisper",
	"Mudo, sussurre baixinho": "Muted, whisper softly",
	"Microfone mudo": "Microphone muted",
	"A sua vez passa": "Your turn is skipped",
	"Quantas luzinhas acesas?": "How many lights are on?",
	"Isso: obedeceu, mesmo com tudo ligado": "Right: it obeyed, even with everything on",
	"Treino — não vale ponto": "Practice — no points",
	"Valendo!": "For real!",
	"Treino": "Practice",
	"Treino ✓": "Practice ✓",
	"Lidera": "Leads",
	"A última sala": "The last room",
	"As salas, de trás para a frente": "The rooms, last to first",
	"O sorteio": "The draw",
	"Virada!": "Comeback!",
	# a pausa
	"Continuar": "Continue",
	"Empate!": "Tie!",
	"Vocês venceram!": "You won!",
	"Não deu desta vez.": "Not this time.",
	"Voltar ao lobby": "Back to the lobby",
	"Sair do jogo": "Quit the game",
	"Escolher": "Choose",
	# o que as dicas das salas dizem fora do caminho comum
	"Chave": "Key",
	"Trace o zeta, em ordem": "Trace the zeta, in order",
	"Trace o mi, em ordem": "Trace the mu, in order",
	"Este controle não tem touchpad": "This controller has no touchpad",
	"Sem touchpad": "No touchpad",
	"Peça forjada!": "Piece forged!",
	"Sacuda para baixo": "Shake downward",
	"Atravessou!": "Crossed!",
	"Contra o vento": "Against the wind",
	"Recarrega": "Reload",
	"Chegou": "Arrived",
	"Repetir": "Repeat",
	"Lugar": "Seat",
	# o botão, em toda dica: "Botão ✕ (Iniciar)"
	"Botão": "Button",
	"Fechar": "Close",
	# as frases montadas que ainda não tinham tradução (o tropeço, os poucos, a pedra, o chamado)
	"A pedra era da esquerda": "The stone was on the left",
	"A pedra era da direita": "The stone was on the right",
	"Você contra 2 bonecos": "You against 2 dummies",
	"1 contra 1": "1 against 1",
	"2 contra 1 + boneco": "2 against 1 + dummy",
	"Martela": "Hammer",
	"O chamado": "The call",
	"Sem resposta": "No answer",
	"Parede e clique": "Wall and click",
	"O tremor": "The tremor",
	"O peso": "The weight",
	"Solto": "Loose",
	"Um baque macio": "A soft thud",
	"Quatro estalos": "Four clicks",
	"Um golpe que ressoa": "A ringing blow",
	"Duas ondas": "Two waves",
	# o kit do minigame (H04)
	"O Martelo de Hefesto": "Hephaestus's Hammer",
	"Bata!": "Strike!",
	# o título da fita (G01)
	"Nenhum controle encontrado": "No controller found",
	"Jogar no teclado": "Play on the keyboard",
	"Gravar": "Record",
	"Nove salas, quatro cavaleiros": "Nine rooms, four knights",
	# a construção do cavaleiro (G02)
	"Boneco": "Figure",
	"Arma": "Weapon",
	"Arma ou amuleto": "Weapon or charm",
	"Nome": "Name",
	"Mãos livres": "Empty hands",
	"Martelo": "Hammer",
	"Escudo": "Shield",
	"Fole": "Bellows",
	"Lanterna": "Lantern",
	"Diapasão": "Tuning fork",
	"Âncora": "Anchor",
	"Fosco": "Matte",
	"Polido": "Polished",
	"Riscado": "Scratched",
	"Dourado": "Golden",
	"Cromado": "Chrome",
	"Néon": "Neon",
	"Tocar a faixa": "Play the track",
	"Tocar A Prova": "Play The Trial",
	"Partida": "Match",
	"Prova de Fogo": "Trial by Fire",
	"Forjar": "Forge",
	"Sortear": "Shuffle",
	"Forjado": "Forged",
	"Guardado": "Saved",
	# o teclado do nome (G09): o nome da pessoa não passa pela tabela
	"Escrever": "Write",
	"Apagar": "Erase",
}

## Os textos com número: [padrão, substituição] (a substituição usa $1, $2…).
const EN_PADROES := [
	["^(.+) na forja$", "$1 in the forge"],
	["^Recorde da noite: P(\\d)$", "Record of the night: P$1"],
	["^S(\\d) · 1 FAIXA$", "S$1 · 1 TRACK"],
	["^S(\\d) · (\\d+) FAIXAS$", "S$1 · $2 TRACKS"],
	["^S(\\d) · EM BREVE$", "S$1 · COMING SOON"],
	["^(\\d+) pontos$", "$1 points"],
	["^Terminou · (\\d+)$", "Done · $1"],
	["^Runa (\\d+) de (\\d+) · (\\d+)$", "Rune $1 of $2 · $3"],
	["^(\\d+) · viga (\\d+)%$", "$1 · beam $2%"],
	["^(\\d+) · sinos (\\d+) de (\\d+)$", "$1 · bells $2 of $3"],
	["^(\\d+) · pedra (\\d+) de (\\d+)$", "$1 · stone $2 of $3"],
	["^(\\d+) · ponto (\\d+) de (\\d+)$", "$1 · point $2 of $3"],
	["^(\\d+) · carimbo (\\d+) de (\\d+)$", "$1 · stamp $2 of $3"],
	["^(\\d+) · junte$", "$1 · pinch"],
	["^(\\d+) · abra$", "$1 · spread"],
	["^Onda (\\d+) de (\\d+) · golpe (\\d+) de (\\d+)$", "Wave $1 of $2 · blow $3 of $4"],
	["^Rodada (\\d+) de (\\d+) · (\\d+) ✓$", "Round $1 of $2 · $3 ✓"],
	["^Vida (\\d+)% · (\\d+) ✓$", "Life $1% · $2 ✓"],
	["^(Brasa|Maré) · vida (\\d+) · (\\d+) balas$", "$1 · life $2 · $3 bullets"],
	["^(Brasa|Maré) · (\\d+) pontos$", "$1 · $2 points"],
	["^(Brasa|Maré) · derrubado$", "$1 · knocked down"],
	["^Brasa (\\d+) × (\\d+) Maré · (\\d+:\\d+)$", "Ember $1 × $2 Tide · $3"],
	["^Brasa (\\d+) × (\\d+) Maré$", "Ember $1 × $2 Tide"],
	["^A partida começa em (\\d+)$", "The match starts in $1"],
	["^A prova final, às cegas$", "The final blind test"],
	["^(\\d+) luzinhas?$", "$1 lights"],
	["^1 bala$", "1 bullet"],
	["^(\\d+) balas$", "$1 bullets"],
	["^Aperte R2 e sinta: que arma é\\?$", "Press R2 and feel: which weapon is it?"],
	["^Aperte R2 e sinta o gatilho\\.$", "Press R2 and feel the trigger."],
	["^Faltam (\\d+) jogadores ficarem prontos$", "$1 players still need to get ready"],
	["^Falta 1 jogador ficar pronto$", "1 player still needs to get ready"],
	["^(\\d+) controles?  ·  (.*)$", "$1 controllers  ·  $2"],
	["^(\\d+) controles?$", "$1 controllers"],
	["^(\\d+) simulados?$", "$1 simulated"],
	["^Seção (\\d)$", "Section $1"],
	["^DualSense simulado (\\d)$", "Simulated DualSense $1"],
	["^Partida · sala (\\d+) de (\\d+)$", "Match · room $1 of $2"],
	["^Prova de Fogo · sala (\\d+) de (\\d+)$", "Trial by Fire · room $1 of $2"],
	["^P(\\d) venceu a noite$", "P$1 won the night"],
	["^P(\\d) venceu!$", "P$1 wins!"],
	["^P(\\d) e P(\\d) empatam!$", "P$1 and P$2 tie!"],
	["^(.+) · desempate: (.+)$", "$1 · tiebreak: $2"],
	["^(.+) dividem a noite$", "$1 share the night"],
	["^P(\\d) escolhe$", "P$1 chooses"],
	["^P(\\d) pausou$", "P$1 paused"],
	["^(\\d+) salas$", "$1 rooms"],
	["^As 9 salas$", "All 9 rooms"],
	["^Uns (\\d+) min$", "About $1 min"],
	["^A seguir: (.+)$", "Next: $1"],
	["^Depois d'?(?:'|os |as )?(.+) · sala (\\d+) de (\\d+)$", "After $1 · room $2 of $3"],
	["^(\\d+)º  \\+(\\d+)$", "#$1  +$2"],
	["^(\\d+)º$", "#$1"],
	["^(\\d+) s$", "$1 s"],
	["^(\\d+) ✓ · ritmo (\\d+)$", "$1 ✓ · rhythm $2"],
	["^Canto (\\d+) de (\\d+)$", "Song $1 of $2"],
	["^Trecho (\\d+) de (\\d+) · (\\d+) ✓$", "Stretch $1 of $2 · $3 ✓"],
	["^Treino · (.+)$", "Practice · $1"],
	["^Chegou · (\\d+) ✓$", "Arrived · $1 ✓"],
	["^Isso: era do P(\\d)$", "Right: it was P$1's"],
	["^O chamado · P(\\d)$", "The call · P$1"],
	["^Quieto: é a vez do P(\\d)$", "Quiet: it's P$1's turn"],
	# os rodapés das perguntas às cegas (Modo bancada): o mais certo antes do mais largo
	["^Sem resposta — era seu$", "No answer — it was yours"],
	["^Sem resposta — era da TV$", "No answer — it was the TV"],
	["^Sem resposta — era do P(\\d)$", "No answer — it was P$1's"],
	["^Não — era seu$", "No — it was yours"],
	["^Não — era da TV$", "No — it was the TV"],
	["^Não — era do P(\\d)$", "No — it was P$1's"],
	["^Sem resposta — eram (\\d+)$", "No answer — there were $1"],
	["^Sem resposta — era (.+)$", "No answer — it was $1"],
	["^Sem resposta — estava (.+)$", "No answer — it was $1"],
	["^Era (.+) \\((.+)\\)$", "It was $1 ($2)"],
	["^Não — o jogo acendeu (\\d+)$", "No — the game lit $1"],
	["^Não — o jogo mandou (.+)$", "No — the game sent $1"],
]


## O texto na língua escolhida.
static func traduzir(s: String) -> String:
	if idioma == "pt_BR" or s == "":
		return s
	if EN.has(s):
		return EN[s]
	# A tabela se escreve com maiúscula; a mesma frase no meio de outra ("era
	# pistola", o grupo de um padrão) acha a entrada pela forma maiúscula e
	# volta com a inicial minúscula.
	var inicial := s.substr(0, 1)
	if inicial != inicial.to_upper():
		var grande := inicial.to_upper() + s.substr(1)
		if EN.has(grande):
			var en: String = EN[grande]
			if en.length() > 1 and en.substr(1, 1) == en.substr(1, 1).to_lower():
				return en.substr(0, 1).to_lower() + en.substr(1)
			return en
	if _padroes.is_empty():
		for par in EN_PADROES:
			var r := RegEx.new()
			r.compile(par[0])
			_padroes.append([r, par[1]])
	for par in _padroes:
		var r: RegEx = par[0]
		var m := r.search(s)
		if m:
			var saida: String = par[1]
			for g in range(m.get_group_count(), 0, -1):
				saida = saida.replace("$%d" % g, traduzir(m.get_string(g)))
			return saida
	return s
