class_name Traducoes
extends RefCounted
## As telas em inglês (o Sprint E). O português é a língua do jogo e a chave:
## cada texto que o Desenho e o Glifo desenham passa por `traduzir`, que acha
## a frase exata na tabela ou, com números no meio, um dos padrões. O que não
## tem tradução sai como está.
##
## O porquê de cada veredito (o que foi medido) e o relatório vêm do núcleo em
## C e ficam em português.

static var idioma := "pt_BR"
static var _padroes: Array = []  # [RegEx, substituição]

const EN := {
	# o título, os créditos, o lobby
	"Quatro DualSense no mesmo sofá.": "Four DualSense on the same couch.",
	"Nenhum controle.": "No controller.",
	"Conecte um DualSense por USB ou Bluetooth.": "Connect a DualSense over USB or Bluetooth.",
	"jogar no teclado (Enter)": "play on the keyboard (Enter)",
	"O módulo nativo não carregou: só o teclado joga.": "The native module did not load: only the keyboard plays.",
	"Compile com scripts/compilar.sh linux.": "Build it with scripts/compilar.sh linux.",
	"começar": "start",
	"créditos": "credits",
	"voltar": "back",
	"Quem joga": "Who plays",
	"Aperte ✕ no seu controle para entrar.": "Press ✕ on your controller to join.",
	"Todos prontos": "Everyone ready",
	"entrar": "join",
	"pronto": "ready",
	"sair": "leave",
	"opções": "options",
	"simulado": "simulated",
	"·  simulado": "·  simulated",
	"SDL virtual": "SDL virtual",
	"Luz": "Light",
	"humano": "human",
	"orc": "orc",
	"espada e escudo": "sword and shield",
	"lança": "spear",
	"lança e escudo": "spear and shield",
	"poção": "potion",
	"sem controle": "no controller",
	"O controle saiu.": "The controller left.",
	"Religue o mesmo para voltar.": "Plug the same one back in to return.",
	"liberar o lugar": "free the seat",
	# o HUD e o salão
	"diagnóstico": "diagnostics",
	"pausa": "pause",
	"em breve": "soon",
	"botões, analógicos e gatilhos": "buttons, sticks and triggers",
	"giroscópio e acelerômetro": "gyroscope and accelerometer",
	"touchpad: dois dedos e clique": "touchpad: two fingers and click",
	"vibração e barra de luz": "rumble and light bar",
	"gatilhos adaptativos": "adaptive triggers",
	"microfone e mudo": "microphone and mute",
	"háptica por áudio": "audio haptics",
	"alto-falante": "speaker",
	"tudo junto, duas equipes · □ a partida · △ a Prova de Fogo": "everything at once, two teams · □ match · △ Trial by Fire",
	# as salas: o nome e o verbo
	"A Centelha": "The Spark",
	"A Viga": "The Beam",
	"O Molde": "The Mold",
	"O Impacto": "The Impact",
	"A Galeria": "The Gallery",
	"O Canto": "The Song",
	"Os Caminhos": "The Paths",
	"Caminhos": "The Paths",
	"A Voz": "The Voice",
	"A Prova": "The Trial",
	"Aperte o botão da runa antes do anel fechar.": "Press the rune's button before the ring closes.",
	"Equilibre, mire e martele com o controle.": "Balance, aim and hammer with the controller.",
	"O touchpad é o molde: trace, abra, carimbe.": "The touchpad is the mold: trace, open, stamp.",
	"Sinta o golpe e levante o escudo do lado.": "Feel the blow and raise the shield on that side.",
	"Sinta o gatilho, diga a arma, atire.": "Feel the trigger, name the weapon, shoot.",
	"Ouça: o canto saiu da sua mão?": "Listen: did the song come from your hand?",
	"Sinta o chão na mão e diga qual é.": "Feel the ground in your hand and name it.",
	"Chame o guardião, fique mudo, olhe a luz.": "Call the guardian, mute, look at the light.",
	"Brasa contra Maré, com tudo ligado.": "Ember against Tide, with everything on.",
	# as features
	"Botões": "Buttons",
	"Analógicos": "Sticks",
	"Gatilhos analógicos": "Analog triggers",
	"Giroscópio": "Gyroscope",
	"Acelerômetro": "Accelerometer",
	"Touchpad, dois dedos": "Touchpad, two fingers",
	"Touchpad, clique": "Touchpad, click",
	"Motor forte (esquerda)": "Strong motor (left)",
	"Motor fraco (direita)": "Weak motor (right)",
	"Vibração só no controle certo": "Rumble only on the right controller",
	"Lightbar": "Light bar",
	"Gatilho: resistência": "Trigger: resistance",
	"Gatilho: arma": "Trigger: weapon",
	"Gatilho: vibração": "Trigger: vibration",
	"LEDs de jogador": "Player LEDs",
	"Alto-falante do controle": "Controller speaker",
	"Háptica por áudio": "Audio haptics",
	"Microfone": "Microphone",
	"Mudo do microfone": "Microphone mute",
	"LED do microfone": "Microphone LED",
	"Tudo junto": "Everything at once",
	# o aviso, o jogo e o veredito
	"✕ quando pronto": "✕ when ready",
	"aguardando": "waiting",
	"✓ pronto": "✓ ready",
	"✓ PRONTO": "✓ READY",
	"trocar": "switch",
	"testar": "test",
	"não achado": "not found",
	"✓ PASSOU": "✓ PASSED",
	"✗ FALHOU": "✗ FAILED",
	"— NÃO MEDIDO": "— NOT MEASURED",
	"voltar ao salão": "back to the hall",
	"seguir a Prova de Fogo": "continue the Trial by Fire",
	"o livro da sessão": "the session book",
	"o placar": "the scoreboard",
	"prova às cegas: o diagnóstico volta no fim da sala": "blind test: diagnostics return at the end of the room",
	# A Centelha, A Viga, O Molde
	"clique quando brilhar": "click when it glows",
	"gire para mirar": "turn to aim",
	"incline contra o vento": "lean against the wind",
	"mira": "aim",
	"arremessa": "throw",
	"atira": "shoot",
	"trace o eta, o H de Hefesto": "trace the eta, Hefesto's H",
	"trace o lambda, em ordem": "trace the lambda, in order",
	"trace o sigma, em ordem": "trace the sigma, in order",
	"dois dedos: afaste": "two fingers: spread",
	"agora junte os dedos": "now pinch",
	# O Impacto, A Galeria
	"Que cor está a sua luz?": "What color is your light?",
	"âmbar": "amber",
	"ciano": "cyan",
	"violeta": "violet",
	"branco": "white",
	"isso: a luz obedeceu": "right: the light obeyed",
	"isso: as luzinhas obedeceram": "right: the lights obeyed",
	"isso: o peso": "right: the weight",
	"isso: o tremor": "right: the tremor",
	"isso: parede e clique": "right: wall and click",
	"isso: solto": "right: loose",
	"O armeiro recarregou. Quantas luzinhas acesas?": "The armorer reloaded. How many lights are on?",
	"pistola": "pistol",
	"metralhadora": "machine gun",
	"arco": "bow",
	"sem arma": "no weapon",
	"recarregue": "reload",
	"martelada!": "hammer blow!",
	"esquerda": "left",
	"direita": "right",
	# a partida, o placar, o pódio
	"A partida": "The match",
	"Salas": "Rooms",
	"Ordem": "Order",
	"Ritmo": "Pace",
	"a do percurso": "the route's",
	"sorteada": "shuffled",
	"primeira vez": "first time",
	"normal": "normal",
	"rápido": "fast",
	"linha": "row",
	"O placar": "The scoreboard",
	"O pódio": "The podium",
	"nesta sala": "this room",
	"da noite": "tonight",
	"salas vencidas": "rooms won",
	"outra partida": "another match",
	"o pódio": "the podium",
	# as opções
	"Opções": "Options",
	"Sessão": "Session",
	"Gatilhos": "Triggers",
	"Vibração": "Rumble",
	"Volume da TV": "TV volume",
	"Volume do controle": "Controller volume",
	"Movimento da câmera": "Camera motion",
	"Flashes": "Flashes",
	"Tela": "Screen",
	"Texto": "Text",
	"Idioma": "Language",
	"desligado": "off",
	"fraco": "weak",
	"forte": "strong",
	"ligado": "on",
	"ligados": "on",
	"desligados": "off",
	"janela": "window",
	"tela cheia": "fullscreen",
	"grande": "large",
	"Tempo": "Timing",
	"tocar no tempo": "tap on the beat",
	# O Canto, Os Caminhos, A Voz, A Prova
	"Alto-falante": "Speaker",
	"O canto saiu do seu controle?": "Did the song come from your controller?",
	"ouça: de onde vem?": "listen: where is it coming from?",
	"foi no meu": "it was mine",
	"não foi": "it wasn't",
	"repita o ritmo": "repeat the rhythm",
	"isso: era da TV": "right: it was the TV",
	"isso: era seu": "right: it was yours",
	"placa virtual do controle simulado": "virtual card of the simulated controller",
	"simulado: quatro canais, como no cabo": "simulated: four channels, as on the cable",
	"Que chão é esse?": "What ground is this?",
	"ande e sinta o chão": "walk and feel the ground",
	"grama": "grass",
	"cascalho": "gravel",
	"metal": "metal",
	"água": "water",
	"não senti": "didn't feel it",
	"tropeçou!": "tripped!",
	"isso: um baque macio": "right: a soft thud",
	"isso: quatro estalos": "right: four clicks",
	"isso: um golpe que ressoa": "right: a ringing blow",
	"isso: duas ondas": "right: two waves",
	"isso: a pedra era da esquerda": "right: the stone was on the left",
	"isso: a pedra era da direita": "right: the stone was on the right",
	"treino: sinta um baque macio": "practice: feel a soft thud",
	"treino: sinta quatro estalos": "practice: feel four clicks",
	"treino: sinta um golpe que ressoa": "practice: feel a ringing blow",
	"treino: sinta duas ondas": "practice: feel two waves",
	"Como está a luz do microfone?": "How is the microphone light?",
	"acesa": "on",
	"apagada": "off",
	"piscando": "blinking",
	"olhe o controle…": "look at the controller…",
	"a luz do microfone": "the microphone light",
	"silêncio": "silence",
	"silêncio: o guardião dorme": "silence: the guardian sleeps",
	"o silêncio de todos": "everyone's silence",
	"quieto": "quiet",
	"sua vez: chame!": "your turn: call!",
	"fale alto: chame o guardião": "speak up: call the guardian",
	"chamou ✓": "called ✓",
	"fique mudo": "mute",
	"mudo": "muted",
	"mudo ✓": "muted ✓",
	"o mudo": "the mute",
	"mudos, sussurrem": "muted, whisper",
	"mudo, sussurre baixinho": "muted, whisper softly",
	"microfone mudo": "microphone muted",
	"mudo no sistema: a sua vez passa": "muted by the system: your turn is skipped",
	"Quantas luzinhas acesas?": "How many lights are on?",
	"isso: obedeceu, mesmo com tudo ligado": "right: it obeyed, even with everything on",
	"treino — não vale ponto": "practice — no points",
	"Valendo!": "For real!",
	"treino": "practice",
	"treino ✓": "practice ✓",
	"lidera": "leads",
	"a última sala": "the last room",
	"as salas, de trás para a frente": "the rooms, last to first",
	"o sorteio": "the draw",
	"virada!": "comeback!",
	# a pausa
	"Pausa": "Pause",
	"Continuar": "Continue",
	"Diagnóstico": "Diagnostics",
	"O livro da sessão": "The session book",
	"Voltar ao salão": "Back to the hall",
	"Voltar ao lobby": "Back to the lobby",
	"Sair do jogo": "Quit the game",
	"escolher": "choose",
}

## Os textos com número: [padrão, substituição] (a substituição usa $1, $2…).
const EN_PADROES := [
	["^(\\d+) pontos$", "$1 points"],
	["^terminou · (\\d+)$", "done · $1"],
	["^runa (\\d+) de (\\d+) · (\\d+)$", "rune $1 of $2 · $3"],
	["^(\\d+) · viga (\\d+)%$", "$1 · beam $2%"],
	["^(\\d+) · sinos (\\d+) de (\\d+)$", "$1 · bells $2 of $3"],
	["^(\\d+) · pedra (\\d+) de (\\d+)$", "$1 · stone $2 of $3"],
	["^(\\d+) · ponto (\\d+) de (\\d+)$", "$1 · point $2 of $3"],
	["^(\\d+) · carimbo (\\d+) de (\\d+)$", "$1 · stamp $2 of $3"],
	["^(\\d+) · junte$", "$1 · pinch"],
	["^(\\d+) · abra$", "$1 · spread"],
	["^onda (\\d+) de (\\d+) · golpe (\\d+) de (\\d+)$", "wave $1 of $2 · blow $3 of $4"],
	["^rodada (\\d+) de (\\d+) · (\\d+) ✓$", "round $1 of $2 · $3 ✓"],
	["^vida (\\d+)% · (\\d+) ✓$", "life $1% · $2 ✓"],
	["^(Brasa|Maré) · vida (\\d+) · (\\d+) balas$", "$1 · life $2 · $3 bullets"],
	["^(Brasa|Maré) · (\\d+) pontos$", "$1 · $2 points"],
	["^(Brasa|Maré) · derrubado$", "$1 · knocked down"],
	["^Brasa (\\d+) × (\\d+) Maré · (\\d+:\\d+)$", "Ember $1 × $2 Tide · $3"],
	["^Brasa (\\d+) × (\\d+) Maré$", "Ember $1 × $2 Tide"],
	["^a partida começa em (\\d+)$", "the match starts in $1"],
	["^a prova final, às cegas$", "the final blind test"],
	["^(\\d+) luzinhas?$", "$1 lights"],
	["^Aperte R2 e sinta: que arma é\\?$", "Press R2 and feel: which weapon is it?"],
	["^Aperte R2 e sinta o gatilho\\.$", "Press R2 and feel the trigger."],
	["^Faltam (\\d+) jogadores ficarem prontos$", "$1 players still need to get ready"],
	["^Falta 1 jogador ficar pronto$", "1 player still needs to get ready"],
	["^(\\d+) controles?  ·  (.*)$", "$1 controllers  ·  $2"],
	["^(\\d+) controles?$", "$1 controllers"],
	["^(\\d+) simulados?$", "$1 simulated"],
	["^FORJA (\\S+)  ·  relatórios ao lado do jogo$", "FORJA $1  ·  reports next to the game"],
	["^DualSense simulado (\\d)$", "Simulated DualSense $1"],
	["^Partida · sala (\\d+) de (\\d+)$", "Match · room $1 of $2"],
	["^Prova de Fogo · sala (\\d+) de (\\d+)$", "Trial by Fire · room $1 of $2"],
	["^P(\\d) venceu a noite$", "P$1 won the night"],
	["^(.+) · desempate: (.+)$", "$1 · tiebreak: $2"],
	["^(.+) dividem a noite$", "$1 share the night"],
	["^P(\\d) escolhe$", "P$1 chooses"],
	["^P(\\d) pausou$", "P$1 paused"],
	["^(\\d+) salas$", "$1 rooms"],
	["^as 9 salas$", "all 9 rooms"],
	["^uns (\\d+) min$", "about $1 min"],
	["^a seguir: (.+)$", "next: $1"],
	["^depois d'?(?:'|os |as )?(.+) · sala (\\d+) de (\\d+)$", "after $1 · room $2 of $3"],
	["^(\\d+)º  \\+(\\d+)$", "#$1  +$2"],
	["^(\\d+)º$", "#$1"],
	["^(\\d+) s$", "$1 s"],
	["^(\\d+) ✓ · ritmo (\\d+)$", "$1 ✓ · rhythm $2"],
	["^canto (\\d+) de (\\d+)$", "song $1 of $2"],
	["^trecho (\\d+) de (\\d+) · (\\d+) ✓$", "stretch $1 of $2 · $3 ✓"],
	["^treino · (.+)$", "practice · $1"],
	["^chegou · (\\d+) ✓$", "arrived · $1 ✓"],
	["^isso: era do P(\\d)$", "right: it was P$1's"],
	["^o chamado · P(\\d)$", "the call · P$1"],
	["^quieto: é a vez do P(\\d)$", "quiet: it's P$1's turn"],
]


## O texto na língua escolhida.
static func traduzir(s: String) -> String:
	if idioma == "pt_BR" or s == "":
		return s
	if EN.has(s):
		return EN[s]
	if _padroes.is_empty():
		for par in EN_PADROES:
			var r := RegEx.new()
			r.compile(par[0])
			_padroes.append([r, par[1]])
	for par in _padroes:
		var r: RegEx = par[0]
		var m := r.search(s)
		if m:
			var saida: String = par[1]
			for g in range(m.get_group_count(), 0, -1):
				saida = saida.replace("$%d" % g, traduzir(m.get_string(g)))
			return saida
	return s
